server:
  port: 9999

app: myApp

spring:
  application:
    name: test
    version: v1

  database1:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    userName: sa1
    password: password

  database2:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    userName: sa2
    password: password

management:
  endpoints:
    web:
      exposure:
        include: env,health

component1:
  nom: Laurent
  prenom: Robineau

---

spring:
  profiles: test

server:
  port: 9998

app: myAppTest

